export const types = {
  CATS: "CATS",
  ERROR: "ERROR",
  PENDING: "PENDING",
  AUTH_SUCCESS: 'AUTH_SUCCESS', 
  LOADING: 'LOADING', 
  USER_ERROR: 'USER_ERROR',
  USER_SUCCESS: 'USER_SUCCESS',
  LOG_OUT: 'LOG_OUT', 
  LOG_IN: 'LOG_IN' 
};
